language: cpp
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
script:
  - mkdir build && cd build && cmake -D CMAKE_INSTALL_PREFIX=. ..; make -j8; make install
